name: CI-test

on:
  push:
    branches: master
    
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout the repository 
      uses: actions/checkout@v2 
    - name: Testing pipeline 
      run: | 
        echo 'starting the pipeline' 
        mkdir bin 
        mkdir lib 
        curl https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.5.2/junit-jupiter-engine-5.5.2.jar -o lib/junit-jupiter-engine-5.5.2.jar 
        curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.5.2/junit-platform-console-standalone-1.5.2.jar -o lib/junit-platform-console-standalone-1.5.2.jar 
        javac -d bin/ src/*.java 
        javac -d bin -cp bin:lib/junit-platform-console-standalone-1.5.2.jar test/* 
        java -jar lib/junit-platform-console-standalone-1.5.2.jar --class-path bin --scan-class-path
